### ISSUE TITLE
Disqus is not added to blog post

### ISSUE THREAD

**Issue by AlonAmsalem** [carlwoodhouse/Orchard.Cw.Disqus#2]
Hi
I've enabled the module and added disqus to BlogPost content type but disqus is not visible.
html is not rendered
thanks

**Comment by AlonAmsalem** [comment]
using orchard 1.8.1

**Comment by carlwoodhouse** [comment]
Is your placement setup properly? though it should display by default.

Hadn't tested on 1.8.1, i was using on 1.7.2 but i've just updated it to work with 1.9.0 and you can now change the settings in the admin, rather then editing a view. Please try the new version if you never got it working :)
