### ISSUE TITLE
Using content item ID as page identifier

### ISSUE THREAD

**Issue by Piedone** [carlwoodhouse/Orchard.Cw.Disqus#5]
Since Disqus is loaded via a content part I think it would be useful to use the content item's ID as `page.identifier` in a configuration block (see below). This would allow displaying the same comment thread even if the site is e.g. run locally from a production snapshot.

Maybe it would be also good to use the content item's `DisplayUrl` as `page.url` for a similar reason.

Also see: https://help.disqus.com/customer/en/portal/articles/2158629

```
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
```

**Comment by Piedone** [comment]
And BTW if you don't want IIS Express to open when you attach the debugger to an IIS process running Orchard with this module then change the relevant section of the csproj file to this:

```
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}">
        <WebProjectProperties>
          <UseIIS>False</UseIIS>
          <AutoAssignPort>True</AutoAssignPort>
          <DevelopmentServerPort>45979</DevelopmentServerPort>
          <DevelopmentServerVPath>/</DevelopmentServerVPath>
          <IISUrl></IISUrl>
          <NTLMAuthentication>False</NTLMAuthentication>
          <UseCustomServer>True</UseCustomServer>
          <CustomServerUrl>http://orchard.codeplex.com</CustomServerUrl>
          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
        </WebProjectProperties>
      </FlavorProperties>
    </VisualStudio>
  </ProjectExtensions>
```

**Comment by carlwoodhouse** [comment]
will look into these over the weekend

**Comment by Piedone** [comment]
Thank you!

**Comment by carlwoodhouse** [comment]
sorted

**Comment by Piedone** [comment]
Thank you, I added some comments on your commit.
