### ISSUE TITLE
Add setting to toggle comments on/off per content item

### ISSUE THREAD

**Issue by rtpHarry** [carlwoodhouse/Orchard.Cw.Disqus#7]
At the moment if you attach this to a content item (for example BlogPost) it will be displayed for every blog post no matter what.

With the built in comments system you can opt-out on a per blog post basis with a checkbox.

**Comment by carlwoodhouse** [comment]
will add this :)

**Comment by carlwoodhouse** [comment]
This is in the latest release @rtpHarry
