### ISSUE TITLE
Documentation - How to Install?

### ISSUE THREAD

**Issue by atiq-cs** [carlwoodhouse/Orchard.Cw.Disqus#8]
I have installed it by putting it into Module directory and then enabling it from "Modules" secction of the dashboard. I have set my short name. However, I am getting the mentioned error..

    We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

**Comment by atiq-cs** [comment]
It's working. I had to configure the site on disqus portal. Previously, I tried with my perrsonal disqus username that is why it did not work. My first try with disqus, so my apologies. Thanks for the great module.

**Comment by carlwoodhouse** [comment]
Glad you figured it out :)
